---
- name: Reconcile compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ authelia_root }}"
    state: present
    build: always
  when: not authelia_first_run | default(true)
  listen: reconcile

- name: Restart authelia
  ansible.builtin.command: docker compose restart authelia
  args:
    chdir: "{{ authelia_root }}"
  changed_when: false
  when: not authelia_first_run | default(true)
  listen: restart authelia

- name: Reload caddy
  ansible.builtin.command: docker exec caddy caddy reload --config /etc/caddy/Caddyfile
  args: {}
  changed_when: false
  when: not authelia_first_run | default(true)
  listen: reload caddy
