---
name: Publish to Ansible Galaxy
on:
  release:
    types:
      - published

jobs:
  import:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7

      - name: Install Ansible
        run: pipx install ansible

      - name: Import versions into Ansible Galaxy
        run: ansible-galaxy import "{{ github.repository_owner }}" "{{ github.event.repository.name }}" --token "{{ secrets.ANSIBLE_GALAXY_TOKEN }}"
